Repository HackMerced/hackmerced-placeholder, pull requests merged in 2018-07, with the labels that each got.

#18 updated index
  assets/img/sections/watch_tower.jpg
  index.html
Labels: bug, enhancement

#24 Feat/meme
  assets/img/sections/watch_tower.jpg
  index.html
  meme.html
Labels: beautiful

#26 Feat/fin
  assets/css/index.css
  index.html
Labels: beautiful, enhancement

#29 icons and sponsors aligned
  assets/css/index.css
  assets/img/sponsors/UltraPress-1.png
  assets/img/sponsors/Vanguard-1.png
  index.html
Labels: enhancement

#33 nav font more visible
  index.html
  meme.html
Labels: enhancement

#35 fixed grammatical errors on main page
  index.html
Labels: enhancement

#36 Feat/fin
  index.html
Labels: enhancement

#37 Feat/jibram
  assets/css/index.css
  index.html
Labels: bug, enhancement

#38 logo update
  .gitignore
  assets/css/index.css
  assets/demo/demo.css
  assets/img/sponsors/ASUCM-1.png
  assets/img/sponsors/DRS.png
  assets/img/sponsors/UCM_IT-1.png
  assets/img/sponsors/Vanguard.jpeg
  index.html
  jquery.firefly.js
  package-lock.json
Labels: beautiful, enhancement

#39 sponsor logo update
  assets/css/index.css
  assets/img/sponsors/ASUCM-1.png
  assets/img/sponsors/UCM_IT-1.png
  index.html
Labels: enhancement

#44 font sizing
  index.html
Labels: enhancement

#46 font updates
  assets/img/sponsors/ASUCM-1.png
  assets/img/sponsors/ASUCM.png
  assets/img/sponsors/Google-1.png
  assets/img/sponsors/Google.png
  assets/img/sponsors/UCM_IT-1.png
  assets/img/sponsors/UCM_IT.png
  assets/img/sponsors/UltraPress-1.png
  assets/img/sponsors/UltraPress.png
  assets/img/sponsors/Vanguard-1.png
  assets/img/sponsors/Vanguard.jpeg
  assets/img/sponsors/Vanguard.png
  index.html
Labels: enhancement
